<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pe.edu.pe.pucp.proyecto</groupId>
        <artifactId>PROYECTO</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>proyecto-dao</artifactId>
    <dependencies>
        <dependency>
            <groupId>pe.edu.pe.pucp.proyecto</groupId>
            <artifactId>proyecto-model</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>pe.edu.pe.pucp.proyecto</groupId>
            <artifactId>proyecto-db-manager</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>


</project>